# Generated by Django 6.0.6 on 2026-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text='Separate tags with commas, e.g. React, Django, PostgreSQL', max_length=300)),
                ('category', models.CharField(choices=[('Full-Stack', 'Full-Stack'), ('Open Source', 'Open Source'), ('Product', 'Product')], default='Full-Stack', max_length=50)),
                ('image_upload', models.ImageField(blank=True, help_text='Upload a screenshot directly (preferred)', null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an image URL instead, if not uploading a file')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="e.g. 'CEO, AgriLink' or 'Frontend Developer, Acme Co'", max_length=150)),
                ('quote', models.TextField()),
                ('author_photo', models.ImageField(blank=True, help_text='Optional headshot', null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
